name: Daily Naukri Apply

# Run daily at 7 PM IST (13:00 UTC) and allow manual trigger
on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Step 2: Install Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt update
          sudo apt install -y google-chrome-stable
          google-chrome --version

      # Step 3: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv selenium openpyxl

      # Step 5: Export secrets as environment variables
      - name: Export Secrets
        run: |
          echo "NAUKRI_EMAIL=${{ secrets.NAUKRI_EMAIL }}" >> $GITHUB_ENV
          echo "NAUKRI_PASSWORD=${{ secrets.NAUKRI_PASSWORD }}" >> $GITHUB_ENV
          echo "SKILLS=${{ secrets.SKILLS }}" >> $GITHUB_ENV
          echo "EXPERIENCE=${{ secrets.EXPERIENCE }}" >> $GITHUB_ENV
          echo "TEXT_VALUE_FOR_BOT=${{ secrets.TEXT_VALUE_FOR_BOT }}" >> $GITHUB_ENV
          echo "HEADLESS=True" >> $GITHUB_ENV

      # Step 6: Run Naukri script
      - name: Run Naukri Script
        run: python naukri_apply.py

      # Step 7: Upload logs
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: naukri-logs
          path: naukri_log.txt

      # Step 8 (Optional): Upload Excel file as artifact
      - name: Upload Applied Jobs Excel
        uses: actions/upload-artifact@v4
        with:
          name: applied-jobs
          path: applied_jobs.xlsx
